sonar.projectKey=jaims-31_bilan-azure-quiz-frontend
sonar.organization=jaims-31
sonar.projectName=bilan-azure-quiz-frontend

sonar.sources=src,.github,Dockerfile,nginx.conf
sonar.exclusions=**/*.spec.ts

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8